import {
  register,
  login,
  logout,
  getUsers,
  getUserById,
  deleteUser,
  updateUser,
  sendOTP,
} from "./user.controller.js";

import {
  createPost,
  getPosts,
  getPostById,
  getPostsByVote,
  getPostsByComment,
  getPostsByTags,
  updatePost,
  deletePost,
  createComment,
  updateComment,
  deleteComment,
  createVote,
  updateVote,
  deleteVote,
} from "./post.controller.js";

import {
  resetPasswordToken,
  resetPassword,
  changePassword,
} from "./resetPassword.controller.js";

export {
  register,
  login,
  logout,
  getUsers,
  getUserById,
  deleteUser,
  updateUser,
  getPosts,
  createPost,
  getPostById,
  getPostsByVote,
  getPostsByComment,
  getPostsByTags,
  updatePost,
  deletePost,
  createComment,
  updateComment,
  deleteComment,
  createVote,
  updateVote,
  deleteVote,
  resetPassword,
  resetPasswordToken,
  changePassword,
  sendOTP,
};
